### ISSUE TITLE
Removing unused imported module.

### ISSUE THREAD

**Issue by 0xPrateek** [salonimehra/image_processing#3]
Hello,
In this [program](https://github.com/salonimehra/image_processing/blob/master/opencsv2_file/ch1/Untitled.ipynb)  of yours you have imported "numpy" which you haven't used in program.
It's better to remove it.

**Comment by 0xPrateek** [comment]
@salonimehra Have you checked this out ?

**Comment by salonimehra** [comment]
Yes ,i was about to use in next code ,but i m sry i uploaded it without
further review ,i ll. Remove it or u can fork and contribute to it ,i will
glad to consider your contribution

**Comment by 0xPrateek** [comment]
That's okay...!
No need to be sorry afterall, its your Repo. :+1: 
You can make these changes by your own. I will surely contribute to your other projects in openCV.
