### ISSUE TITLE
Remove extra code.

### ISSUE THREAD

**Issue by 0xPrateek** [salonimehra/image_processing#4]
Hello,
In your [program](https://github.com/salonimehra/image_processing/blob/master/opencsv2_file/ch1/Untitled.ipynb)
You have written `cv2.imshow("Picture",img)` in your code. which will open window in normal size and set it's title to "Picture".
Also, You have defined  `" cv2.namedWindow("Picture",cv2.WINDOW_NORMAL) "` in your program which does same thing. 
You can delete this line.

**Comment by salonimehra** [comment]
sorry! they appear to be same thing but are not
,cv2.imshow("picture",img)by default shows the image in normal size but one
can give specified size to it where as
cv2.namedWindow("Picture",cv2.WINDOW_NORMAL)
is specifically in normal window size and one cant resize the window in a
specific command line

i wrote these two different code for clear understanding and is lot to
update that repository and will soon update it ,thank you for you response
and your welcomed for further suggestions and forks

**Comment by 0xPrateek** [comment]
I know they seems to be similar to each other but in actual they are way different from themselves.
If you have written this code for understanding all the possible concepts. Then, it's fine.
But, If you are going to use the exact code in some script or anywhere. Then you need to think over it because the thing which the line below does is :: 
`cv2.imshow("Picture",img)`
is exactly similar to this :: 
`cv2.namedWindow("Picture",cv2.WINDOW_NORMAL) `
Since both are similar then why to add extra lines of code.

**Comment by salonimehra** [comment]
No actually i was building a lecture thats why thanks for response

**Comment by 0xPrateek** [comment]
That's fine.
