### ISSUE TITLE
Remove dead code.

### ISSUE THREAD

**Issue by 0xPrateek** [salonimehra/image_processing#5]
Hello,
In your [program](https://github.com/salonimehra/image_processing/blob/master/opencsv2_file/ch2/Untitled.ipynb),
you have written `cv2.waitKey(0)` which is of no use here. Actually cv2.waitKey() is used for holding the output window and checking for the keyboard interruptions for closing the window.
But in this program you are not poping up any window , you are just displaying image matrix values and that's why there is no use of `cv2.waitKey(0)`  here.

**Comment by salonimehra** [comment]
Thank you so much i ll upadte it soon

**Comment by salonimehra** [comment]
cv2.waitkey(time) is used because our operating system will get the command
to keep in hold other process and switch to this process(of showing
image)(waitkey==time taken for os to switch process to showing th image)
after entering any key operating system will get to know that this is the
time where this process is of no use and can be ended thus closses the
window and get back to its old work

**Comment by salonimehra** [comment]
https://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html?highlight=waitkey

for more clearity and research part go through it ,it might help you a lot
,as i too learned from documents

**Comment by 0xPrateek** [comment]
The cv::waitKey(n) function in OpenCV is used to introduce a delay of n milliseconds while rendering images to windows. When it is used as cv::waitKey(0) it returns the key pressed by the user on the active window.
There is nothing like that "our operating system will get the command to keep in hold other process and switch to this process".
You can checkout the documentation as well...
![share1](https://user-images.githubusercontent.com/41592999/52286293-cd32ea80-291c-11e9-9aab-938c796610c5.png)
See the highlighted text

**Comment by 0xPrateek** [comment]
And that's why in program you will mostly see it to be used as :: 
`if cv2.waitKey(0) & 0xFF == 27:
        #operation you want to do (Most of the time [break])
`

**Comment by salonimehra** [comment]
But when i havenot used cv.waitkey my ow was taking large time to open that
window

**Comment by 0xPrateek** [comment]
The best implementation to show up the image in this would be ::
`while True:
      cv2.imshow("Black",black)
      cv2.imshow("Ones",ones)
      cv2.imshow("White",white)

      if cv2.waitKey(0) & 0xFF == 27:
             break
cv2.destroyallwindows() `

Actually, I missed these used cv2.imshow() functions in program. Although the best way to handle image showing activity is above ... :+1:
